export const C = {
  GRAVITY: 1000,
  REBOUND_VELOCITY: -600,
  BOUNCY_REBOUND_VELOCITY: -1200,
  DURATION: 0.016,
  REFRESH_RATE: 62.5,

  PLATFORM_WIDTH: 40,
  PLATFORM_HEIGHT: 10,
  DOODLE_WIDTH: 20,
  DOODLE_HEIGHT: 40,

  ROOT_WIDTH: 450,
  ROOT_HEIGHT: 800,

  SCORE_INCREMENT: 0.1,
  MAINBODY_OFFSET: 25,

  MAX_PLATFORM_X_OFFSET: 175,
  MAX_PLATFORM_Y_OFFSET: 125,
  MINIMUM_PLATFORM_Y_OFFSET: 50,

  PLATFORM_START_X: 225,
  PLATFORM_START_Y: 700,

  PLATFORM_MOVE_X_OFFSET: 2,
  PLATFORM_MOVE_Y_OFFSET: 1,
  MAX_MOVING_PLATFORM_Y_OFFSET: 20,
  CORRECTION_PLATFORM_OFFSET: -50,

  VAR_NORMAL: 1,
  VAR_BOUNCY: 2,
  VAR_MOVING_X: 3,
  VAR_DIS: 4,
  VAR_MOVING_Y: 5,
  VAR_BOUNCE_DISAPPEAR: 6,

  PROBABILITY_CONSTANT: 100,
  PROBABILITY_NORMAL: 45,
  PROBABILITY_BOUNCY: 50,
  PROBABILITY_DISAPPEARING: 68,
  PROBABILITY_MOVING_X: 82,
  PROBABILITY_MOVING_Y: 90,

  COLORS: {
    doodle: "#FFD700",
    normal: "#008000",
    bouncy: "#FF69B4",
    movingX: "#ADD8E6",
    dis: "#B22222",
    movingY: "#00008B",
    bounceDisappear: "#FFFFFF",
    base: "#708090",
    background: "#FFF8DC",
  },
};

C.DOODLE_START_X = C.PLATFORM_START_X;
C.DOODLE_START_Y =
  C.PLATFORM_START_Y - C.PLATFORM_HEIGHT / 2 - C.DOODLE_HEIGHT / 2;
